### ISSUE TITLE
Error while running tar command on vendor.zip

### ISSUE THREAD

**Issue by gamebusterz** [angrbrd/hyperledger-fabric-basics#6]
`tar -xf $GOPATH/src/crowd_fund_chaincode/vendor.zip -C $GOPATH/src/crowd_fund_chaincode/` in README gives the following error 
```
tar: This does not look like a tar archive
tar: Skipping to next header
tar: Exiting with failure status due to previous errors
```

**Comment by adikwidiasmono** [comment]
Have you check the file size of vendor.zip? The correct size for vendor.zip is 149MB
